### ISSUE TITLE
Automate deviations to count how many sites were at 120 pps

### ISSUE THREAD

**Issue by KyleOlivencia** [jasonO6359/flfishltm#16]
If 120 pps = 0 and 60 pps = 100% then: “There were no deviations from the LTM protocol.”
If there are sites with 120 pps then `r pps` = # of 120 pps sites 
`r pps` pasted with “sites were sampled at 120 pps, due to issues reaching target amps at 60 pps”

**Comment by jasonO6359** [comment]
updated create_ltm_report_helpers.R to create var `high_pps` which stores a count of the number of 120 pps samples in the most recent year. 

Then updated create_ltm_report.R to insert a conditional r chunk in the quarto template which adds a deviation bullet if high_pps > 0. 

[commit 1ab9f6c](https://github.com/jasonO6359/flfishltm/commit/1ab9f6c9c16da9edb52a5e2c90f95d7d35d203f5)
