### ISSUE TITLE
You created a code for dealing with missing years. Is there a way to assign that to an object. 

### ISSUE THREAD

**Issue by KyleOlivencia** [jasonO6359/flfishltm#17]
Then for Figure caption: Write a statement that if that object is TRUE meaning there ARE missing years, then paste “Standard surveys were not conducted between (print the range of years) due to XXXXX.”

**Comment by jasonO6359** [comment]
I think this is best handled on a case by case basis. It could be done, but it would require a lot of if-else syntax to create the figure caption... and then it would still require report writer to customize the justification in the quarto template.  I think the lack of data on the figure is enough evidence that standard surveys were not conducted in certain years. If someone (reader of report) wants to know why there is missing data for those years they can go look up previous years reports.  #toomuchsqeezefortoolittlejuice. Good to close?

**Comment by KyleOlivencia** [comment]
good to close
