### ISSUE TITLE
Create objects for specific FHC's

### ISSUE THREAD

**Issue by KyleOlivencia** [jasonO6359/flfishltm#20]
Current code for Lesions:
`r fhc_sum %>% filter(year == max(fhc_sum$year), FishHealthCode1 == \"L\") %>% pull(n)`

Current code for Skeletal Deformities:
`r fhc_sum %>% filter(year == max(fhc_sum$year), FishHealthCode1 == \"S\") %>% pull(n)`

**Comment by jasonO6359** [comment]
https://github.com/jasonO6359/flfishltm/commit/96bacb88ed11e5c2cd756893aa2fe7ee2f6576ba
