### ISSUE TITLE
Output options for species.history

### ISSUE THREAD

**Issue by cander87** [jasonO6359/flfishltm#4]
Add code for user to indicate output as graph, table or both as arguments in species.history function

**Comment by jasonO6359** [comment]
[feature added](https://github.com/jasonO6359/flfishltm/commit/c66bd8073a30897f6246e503f4ca8ba8d96e32c4). 

`return_object` argument added 

example

```
library(flfishltm)
data(newnans)
newnans_sum <-  ltm.data.summary('newnans', newnans)

newnans_collection_table <- species.history(newnans_sum, return_object = "data") # returns data

newnans_collection_fig <- species.history(newnans_sum, return_object = "ggplot") # returns ggplot object
```
